"""Shared data types across SpecTrojan pipeline modules."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable


@dataclass
class TargetFunction:
    """A function in the corpus that we want to validate specs for."""
    name: str
    source: str
    docstring: str
    reference_impl: Callable[..., Any]
    domain: str  # "bio" | "generic"
    input_strategy_hint: str  # natural-language hint for Hypothesis strategy synthesis
    reference_examples: list[tuple[tuple, Any]] = field(default_factory=list)
    explicit_strategy: Any | None = None  # optional Hypothesis SearchStrategy override
    domain_invariant: Callable[..., bool] | None = None  # optional (args, output) -> bool
    public_docstring: str | None = None  # deliberately abstracted docstring for intent-only mode


@dataclass
class CandidateSpec:
    """A spec generated by some model for some target."""
    target_name: str
    model: str          # e.g. "openai:gpt-4o", "gemini:gemini-2.5-pro"
    attempt_id: int
    raw_text: str       # the full text the model produced
    precondition_src: str
    postcondition_src: str
    precondition: Callable[..., bool] | None = None
    postcondition: Callable[..., bool] | None = None
    parse_error: str | None = None


@dataclass
class Mutant:
    """An AST-level mutation of a target function. Used by the mutation-testing baseline."""
    target_name: str
    mutator: str        # e.g. "swap_arith", "off_by_one"
    description: str
    mutated_source: str
    mutated_impl: Callable[..., Any] | None = None


@dataclass
class Disagreement:
    """Two specs disagreed on whether an output is valid for an input — baseline signal."""
    target_name: str
    spec_a: str         # "model:attempt"
    spec_b: str
    inputs: tuple
    reference_output: Any
    spec_a_verdict: bool
    spec_b_verdict: bool


@dataclass
class EvilTwin:
    """A successfully synthesized evil twin — the headline artifact of SpecTrojan.

    An evil twin satisfies the candidate spec (verified under the executor) yet diverges
    behaviorally from the reference on intent-bearing inputs.
    """
    target_name: str
    spec_id: str               # which spec it defeats
    attacker_model: str
    twin_source: str
    distance_score: float      # 0..1, higher = more behaviorally distant from reference
    distance_breakdown: dict   # {hypothesis_disagree_rate, example_disagree_rate, invariant_violation_rate}
    attack_round: int
    prompt_strategy: str       # which diversity strategy produced this twin


@dataclass
class TrojanReport:
    """End-to-end SpecTrojan result for one target function."""
    target_name: str
    specs: list[CandidateSpec]
    evil_twins: list[EvilTwin] = field(default_factory=list)
    metamorphic_robustness: dict[str, float] = field(default_factory=dict)  # spec_id -> robustness
    strengthening_proposals: dict[str, str] = field(default_factory=dict)   # spec_id -> proposed source
    # Baseline counts, for comparison.
    baseline_disagreements: list[Disagreement] = field(default_factory=list)
    baseline_mutation_kill_rates: dict[str, float] = field(default_factory=dict)
